import type { ModelClient, ModelMessage, ModelResponse } from "./types.js";

export class StubExploreModelClient implements ModelClient {
  private readonly seenFocus = new Set<string>();

  async complete(params: { model: string; messages: ModelMessage[] }): Promise<ModelResponse> {
    const last = params.messages.at(-1)?.content ?? "";
    if (/Rank these production-relevant files/i.test(last)) {
      return response(rankFiles(last), params.messages);
    }
    if (isValidationConversation(params.messages)) {
      if (/Command observation:/i.test(last) && /DEEPSEC_STUB_BUG/i.test(last)) {
        return response(
          JSON.stringify({
            action: "final",
            result: {
              verdict: "true-positive",
              reproducible: true,
              interesting: true,
              reasoning: "Stub validation confirmed the deterministic marker in a fresh container.",
              adjustedSeverity: "MEDIUM",
            },
          }),
          params.messages,
        );
      }
      if (/deepsec-stub-bug/i.test(params.messages.map((message) => message.content).join("\n"))) {
        return response(
          JSON.stringify({
            action: "run_command",
            command: "grep -R 'DEEPSEC_STUB_BUG' -n src/main/java | head -20",
            timeoutMs: 30_000,
            reason: "Confirm the reported marker exists in the fresh validation container.",
          }),
          params.messages,
        );
      }
      return response(
        JSON.stringify({
          action: "final",
          result: {
            verdict: "false-positive",
            reproducible: false,
            interesting: false,
            reasoning: "Stub explore model does not validate real findings.",
          },
        }),
        params.messages,
      );
    }
    if (/Command observation:/i.test(last)) {
      if (/DEEPSEC_STUB_BUG/i.test(last)) {
        return response(
          JSON.stringify({
            action: "final",
            result: {
              outcome: "bug",
              title: "Deterministic stub vulnerability marker",
              severity: "MEDIUM",
              confidence: "high",
              vulnSlug: "deepsec-stub-bug",
              lineNumbers: [1],
              description:
                "The deterministic stub marker proves the accepted-finding explore path can carry local evidence through validation.",
              recommendation: "Remove the marker from the fixture source.",
              reproductionSteps: [
                "Run the isolated focus-file inspection command generated by the stub model.",
              ],
              evidence: ["The local command output contained DEEPSEC_STUB_BUG."],
            },
          }),
          params.messages,
        );
      }
      return response(
        JSON.stringify({
          action: "final",
          result: {
            outcome: "no-bug",
            summary: "Stub model inspected the focus file through the gVisor command runner.",
            evidence: ["A bounded local command completed inside the explore container."],
          },
        }),
        params.messages,
      );
    }

    const focusFile = extractFocusFile(params.messages);
    if (focusFile && !this.seenFocus.has(focusFile)) {
      this.seenFocus.add(focusFile);
      if (/Denied/i.test(focusFile)) {
        return response(
          JSON.stringify({
            action: "run_command",
            command: "curl https://example.com/denied",
            timeoutMs: 30_000,
            reason: "Deterministic denied command for harness failure-isolation testing.",
          }),
          params.messages,
        );
      }
      return response(
        JSON.stringify({
          action: "run_command",
          command: `test -f ${shellQuote(focusFile)} && sed -n '1,40p' ${shellQuote(focusFile)}`,
          timeoutMs: 30_000,
          reason: "Verify the copied source is readable through the isolated command runner.",
        }),
        params.messages,
      );
    }

    return response(
      JSON.stringify({
        action: "final",
        result: {
          outcome: "no-bug",
          summary: "Stub model completed without reporting a finding.",
          evidence: ["No additional stub action was required."],
        },
      }),
      params.messages,
    );
  }
}

function isValidationConversation(messages: ModelMessage[]): boolean {
  return messages.some((message) =>
    /validate bounded local security bug reports/i.test(message.content),
  );
}

function rankFiles(prompt: string): string {
  const files = [...prompt.matchAll(/^FILE:\s+(.+)$/gm)].map((m) => m[1]!.trim());
  const rankings = files.slice(0, 12).map((filePath, index) => ({
    filePath,
    score: Math.max(1, 5 - Math.floor(index / 4)),
    reason: "Stub ranking for CLI harness verification.",
  }));
  return JSON.stringify({ rankings });
}

function extractFocusFile(messages: ModelMessage[]): string | null {
  for (const message of messages.slice().reverse()) {
    const match = message.content.match(/^Focus file:\s+(.+)$/m);
    if (match) return match[1]!.trim();
  }
  return null;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function response(text: string, messages: ModelMessage[]): ModelResponse {
  return {
    text,
    raw: { stub: true },
    usage: {
      inputTokens: estimateTokens(messages.map((message) => message.content).join("\n")),
      outputTokens: estimateTokens(text),
    },
  };
}

function estimateTokens(text: string): number {
  return Math.max(1, Math.ceil(text.length / 4));
}
